apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gcloud-eks
  region: us-east-1

nodeGroups:
  - name: gcloud-eks-nodegroup
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
