apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcloud-k8s-deployment

spec:
  selector:
    matchLabels:
      app: gcloud-k8s-deployment
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: gcloud-k8s-deployment
      labels:
        app: gcloud-k8s-deployment
    spec:
      containers:
        - name: gcloud-k8s-deployment
          image: nigelpoulton/k8sbook:edge
          ports:
            - containerPort: 8080
