apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ent-dev
  namespace: dev
  labels:
    app: enterprise

spec:
  replicas: 2
  selector:
    matchLabels:
      app: enterprise
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: enterprise
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: enterprise-ctr
          image: nigelpoulton/k8sbook:text-dev
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ent-prod
  namespace: prod
  labels:
    app: enterprise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enterprise
  template:
    metadata:
      labels:
        app: enterprise
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: enterprise-ctr
          image: nigelpoulton/k8sbook:text-prod
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ent
  namespace: dev
  labels:
    app: enterprise
spec:
  selector:
    app: enterprise
  ports:
    - port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: ent
  namespace: prod

spec:
  selector:
    app: enterprise
  ports:
    - port: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: jump-pod
  namespace: dev

spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: jump-pod
      image: ubuntu
      tty: true
      stdin: true
