apiVersion: v1
kind: Service
metadata:
  name: gcloud-service
  labels:
    app: gcloud-k8s-service

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP

  selector:
    app: gcloud-k8s-deployment
