# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv1
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: test
#   claimRef:
#     namespace: default
#     name: pvc1
#   csi:
#     driver: linodebs.csi.linode.com
#     volumeHandle: "834131-gcloud"
#     fsType: ext4
#     readOnly: false
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: slow
#   annotations:
#     storageclass.kubernetes.io/is-default-class: "true"
# provisioner: kubernetes.io/gce-pd
# parameters:
#   type: pd-standard
#   reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  labels:
    app: pv-pod
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc1
  containers:
    - name: ubuntu-ctr
      image: ubuntu:latest
      command: ["/bin/sh", "-c", "sleep 100000"]
      volumeMounts:
        - mountPath: "/data"
          name: data
