apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dev

data:
  nginx.conf: |
    server {
    listen 80;
    listen [::]:80;
    server_name _;

    location /api {
        proxy_pass http://api-service.dev.svc.cluster.local:5000/;
    }

    location / {
        proxy_pass http://web-service.dev.svc.cluster.local:3000;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    }
